create table jan2013(

	medallion TEXT,
	hack_license TEXT,
	VendorID INTEGER,
	rate_code INTEGER,
	store_and_fwd_flag TEXT,
	pu_time TEXT,
	do_time TEXT,
	pass_count INTEGER,
	duration REAL,
	dist REAL,
	pu_lon REAL,
	pu_lat REAL,
	do_lon REAL,
	do_lat REAL,
	payment_type TEXT,
	fare_amount REAL,
	surcharge REAL,
	mta_tax REAL,
	tip_amount REAL,
	tolls_amount REAL,
	tot_amount REAL,
	avg_speed REAL);